### PR TITLE
chore(deps): allow SF7

### PR DESCRIPTION
**Pull request by simPod**
chore(deps): allow SF7

- Replace require of v6.3 with v6.4
- ~Drop support for SF v5~

### CODE REVIEW

**Comment by kimhemsoe** [comment]
How can we help getting this in?

**Comment by simPod** [comment]
@romm CI is not running for me here but should be fine now

https://github.com/simPod/Valinor-Bundle/actions/runs/7421109427  
https://github.com/simPod/Valinor-Bundle/actions/runs/7421109426

**Comment by romm** [comment]
Thank you @simPod!

**Comment by simPod** [comment]
@romm btw it is missing in release notes

**Comment by romm** [comment]
Hi @simPod, I'm currently investigating for #17 and I was wondering why you came with the [WarmUpCompatibility.php](https://github.com/CuyZ/Valinor-Bundle/pull/12/files#diff-529fbe6c1a3b6f05713e12fc0c8e7c4fbc747a87315f249886e5bfc7c0778afd) file? Adding the `string $buildDir = null` parameter to the `warmUp` method doesn't seem to bother Symfony for version 5.4 and 6.4 (should not be a breaking change for PHP either?).

However, as described in #17, a deprecation message is fired when the parameter is missing in Symfony 6.4.

Could we just add the parameter `$buildDir` to the method? Do you see something wrong with it?

> @romm btw it is missing in release notes

Yeah sorry it's because it was a `chore` commit so not taken in the [changelog script](https://github.com/CuyZ/Valinor-Bundle/blob/master/.changelog). 😅

**Comment by simPod** [comment]
Hm , I see 6.4 does not have that arg either https://github.com/symfony/http-kernel/blob/6.4/CacheWarmer/WarmableInterface.php

I tried to update it https://github.com/CuyZ/Valinor-Bundle/pull/18

**Pull request merged**
